# fly.toml app configuration file generated for escaypr on 2023-09-17T22:00:08+09:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "escaypr"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[build.args]
  BP_KEEP_FILES = "static/*:resources/*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
